site_name: Modified Expensify Docs
theme: readthedocs

nav:
  - Home: 
    - Introduction: index.md
  - Authentication: authentication.md
  - Request format: request_format.md
  - Endpoints: endpoints.md
  - Error codes: errorcodes.md
  - Glossary: glossary.md

 
